version: '3.8'

services:
  backend:
    build:
      context: ./backend2
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend2:/usr/share/nginx/html:ro
    ports:
      - "3000:80"