version: '3.8'

services:
  backend:
    build: ./backend2
    container_name: backend2
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build: ./frontend2
    container_name: frontend2
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
