version: "3.8"

services:
  frontend:
    build: ./frontend2
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend2
    container_name: html_server
    ports:
      - "3001:3001"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - app-network

networks:
  app-network: