version: "3.8"

services:
  backend:
    build: ./backend2
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend2
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - app-network

networks:
  app-network: